{"uid":"4d95983e93f2bea4","name":"test_user_auth[case26]","fullName":"tests.test_user_auth#test_user_auth","historyId":"ad498e1cc5377262384a7018eb8114c7","time":{"start":1753989681401,"stop":1753989681401,"duration":0},"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code","statusTrace":"@pytest.fixture(scope=\"function\")\n    def test_user():\n        \"\"\"创建测试用户\"\"\"\n        username = \"test_\" + ''.join(random.choices(string.ascii_lowercase, k=6))\n        email = f\"{username}@example.com\"\n        password = \"Test123456\"\n    \n        # 发送验证码并断言成功\n        send_response = Request.send_request(\n            \"POST\", \"/auth/send-verify-code\",\n            params={\"email\": email}\n        )\n>       assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\nE       AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\conftest.py:128: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_user","time":{"start":1753989681402,"stop":1753989681701,"duration":299},"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code\n","statusTrace":"  File \"D:\\Anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 128, in test_user\n    assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\n","steps":[{"name":"发送请求：'POST' '/auth/send-verify-code'","time":{"start":1753989681402,"stop":1753989681700,"duration":298},"status":"passed","steps":[],"attachments":[{"uid":"4656a396db22b50f","name":"请求信息","source":"4656a396db22b50f.txt","type":"text/plain","size":52},{"uid":"4293055c42e9c693","name":"请求头","source":"4293055c42e9c693.txt","type":"text/plain","size":45},{"uid":"6d2b27aa1a19b4ed","name":"请求参数","source":"6d2b27aa1a19b4ed.json","type":"application/json","size":44},{"uid":"a7790980824dc5cc","name":"响应信息","source":"a7790980824dc5cc.txt","type":"text/plain","size":14},{"uid":"920e902293c367d","name":"响应体","source":"920e902293c367d.json","type":"application/json","size":81}],"parameters":[{"name":"method","value":"'POST'"},{"name":"endpoint","value":"'/auth/send-verify-code'"},{"name":"headers","value":"None"},{"name":"params","value":"{'email': 'test_lzwqxg@example.com'}"},{"name":"json","value":"None"},{"name":"files","value":"None"},{"name":"token","value":"None"}],"attachmentsCount":5,"shouldDisplayMessage":false,"hasContent":true,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"attachmentsCount":5,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":1}],"testStage":{"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code","statusTrace":"@pytest.fixture(scope=\"function\")\n    def test_user():\n        \"\"\"创建测试用户\"\"\"\n        username = \"test_\" + ''.join(random.choices(string.ascii_lowercase, k=6))\n        email = f\"{username}@example.com\"\n        password = \"Test123456\"\n    \n        # 发送验证码并断言成功\n        send_response = Request.send_request(\n            \"POST\", \"/auth/send-verify-code\",\n            params={\"email\": email}\n        )\n>       assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\nE       AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\conftest.py:128: AssertionError","steps":[],"attachments":[{"uid":"99a3be7d9999f490","name":"log","source":"99a3be7d9999f490.txt","type":"text/plain","size":407},{"uid":"ae43bc4a90b78bbd","name":"stderr","source":"ae43bc4a90b78bbd.txt","type":"text/plain","size":300}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":0},"afterStages":[],"labels":[{"name":"feature","value":"用户认证模块"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_auth"},{"name":"host","value":"CYJ"},{"name":"thread","value":"14532-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_auth"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"case","value":"{'case_id': 'auth_027', 'name': '上传超过2MB的PNG图片', 'method': 'POST', 'url': '/auth/upload/avatar', 'headers': {'Authorization': '', 'Content-Type': 'multipart/form-data'}, 'files': {'file': 'large_avatar.png'}, 'expected_code': 403, 'expected_success': False, 'expected_message': '文件大小不能超过2MB'}"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"4d95983e93f2bea4.json","parameterValues":["{'case_id': 'auth_027', 'name': '上传超过2MB的PNG图片', 'method': 'POST', 'url': '/auth/upload/avatar', 'headers': {'Authorization': '', 'Content-Type': 'multipart/form-data'}, 'files': {'file': 'large_avatar.png'}, 'expected_code': 403, 'expected_success': False, 'expected_message': '文件大小不能超过2MB'}"]}