{"uid":"6ba0322b67bbf82a","name":"test_user_auth[case22]","fullName":"tests.test_user_auth#test_user_auth","historyId":"05647827d506c69a128534dbc4c3bc70","time":{"start":1753987887489,"stop":1753987887489,"duration":0},"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code","statusTrace":"@pytest.fixture(scope=\"function\")\n    def test_user():\n        \"\"\"创建测试用户\"\"\"\n        username = \"test_\" + ''.join(random.choices(string.ascii_lowercase, k=6))\n        email = f\"{username}@example.com\"\n        password = \"Test123456\"\n    \n        # 发送验证码并断言成功\n        send_response = Request.send_request(\n            \"POST\", \"/auth/send-verify-code\",\n            params={\"email\": email}\n        )\n>       assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\nE       AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\conftest.py:128: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_user","time":{"start":1753987887490,"stop":1753987887855,"duration":365},"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code\n","statusTrace":"  File \"D:\\Anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 128, in test_user\n    assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\n","steps":[{"name":"发送请求：'POST' '/auth/send-verify-code'","time":{"start":1753987887490,"stop":1753987887855,"duration":365},"status":"passed","steps":[],"attachments":[{"uid":"424284dedef9feb3","name":"请求信息","source":"424284dedef9feb3.txt","type":"text/plain","size":52},{"uid":"9053a1f8e92f34e8","name":"请求头","source":"9053a1f8e92f34e8.txt","type":"text/plain","size":45},{"uid":"5696b9713cc8d8c7","name":"请求参数","source":"5696b9713cc8d8c7.json","type":"application/json","size":44},{"uid":"f6fea52404753a5b","name":"响应信息","source":"f6fea52404753a5b.txt","type":"text/plain","size":14},{"uid":"d71d69092811084f","name":"响应体","source":"d71d69092811084f.json","type":"application/json","size":81}],"parameters":[{"name":"method","value":"'POST'"},{"name":"endpoint","value":"'/auth/send-verify-code'"},{"name":"headers","value":"None"},{"name":"params","value":"{'email': 'test_uofcyr@example.com'}"},{"name":"json","value":"None"},{"name":"files","value":"None"},{"name":"token","value":"None"}],"attachmentsCount":5,"shouldDisplayMessage":false,"hasContent":true,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"attachmentsCount":5,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":1}],"testStage":{"status":"failed","statusMessage":"AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nassert 500 == 200\n +  where 500 = <Response [500]>.status_code","statusTrace":"@pytest.fixture(scope=\"function\")\n    def test_user():\n        \"\"\"创建测试用户\"\"\"\n        username = \"test_\" + ''.join(random.choices(string.ascii_lowercase, k=6))\n        email = f\"{username}@example.com\"\n        password = \"Test123456\"\n    \n        # 发送验证码并断言成功\n        send_response = Request.send_request(\n            \"POST\", \"/auth/send-verify-code\",\n            params={\"email\": email}\n        )\n>       assert send_response.status_code == 200, f\"发送验证码失败: {send_response.text}\"\nE       AssertionError: 发送验证码失败: {\"success\":false,\"message\":\"发送验证码失败，请稍后重试\",\"data\":null}\nE       assert 500 == 200\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\conftest.py:128: AssertionError","steps":[],"attachments":[{"uid":"a7ef32f88b1483aa","name":"log","source":"a7ef32f88b1483aa.txt","type":"text/plain","size":407},{"uid":"9b669b64616658f9","name":"stderr","source":"9b669b64616658f9.txt","type":"text/plain","size":300}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":0},"afterStages":[],"labels":[{"name":"feature","value":"用户认证模块"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_auth"},{"name":"host","value":"CYJ"},{"name":"thread","value":"22580-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_auth"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"case","value":"{'case_id': 'auth_023', 'name': '新密码与旧密码相同', 'method': 'PUT', 'url': '/auth/userinfo', 'headers': {'Authorization': ''}, 'json': {'oldPassword': 'admin1155', 'newPassword': 'admin1155', 'securityEmail': 'admin1155@example.com', 'verificationCode': '{verify_code}'}, 'expected_code': 403, 'expected_success': False, 'expected_message': '新密码不能与当前密码相同'}"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"6ba0322b67bbf82a.json","parameterValues":["{'case_id': 'auth_023', 'name': '新密码与旧密码相同', 'method': 'PUT', 'url': '/auth/userinfo', 'headers': {'Authorization': ''}, 'json': {'oldPassword': 'admin1155', 'newPassword': 'admin1155', 'securityEmail': 'admin1155@example.com', 'verificationCode': '{verify_code}'}, 'expected_code': 403, 'expected_success': False, 'expected_message': '新密码不能与当前密码相同'}"]}