{"uuid": "d55d5272-8036-4191-8557-b28db7ccb8db", "children": ["f1b64135-5500-44b2-84d0-956f66628644"], "befores": [{"name": "dynamic_test_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'list' object has no attribute 'get'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\test_user_auth.py\", line 78, in dynamic_test_user\n    json_data = case.get(\"json\", {})\n                ^^^^^^^^\n"}, "start": 1754635688297, "stop": 1754635688297}], "start": 1754635688297, "stop": 1754635688312}