{"uuid": "556e4593-daf7-4da4-a8d8-b6fc0582ee99", "children": ["21690111-289a-440c-9d84-9b001c0a2660"], "befores": [{"name": "large_png_image", "status": "passed", "start": 1753972613420, "stop": 1753972613610}], "afters": [{"name": "large_png_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'large_8578.png'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 53, in large_png_image\n    os.remove(img_path)\n"}, "start": 1753972613658, "stop": 1753972613660}], "start": 1753972613420, "stop": 1753972613660}