{"name": "test_user_auth[case18]", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不符：预期401，实际403\nassert 403 == 401\n +  where 403 = <Response [403]>.status_code", "trace": "case = {'case_id': 'auth_019', 'expected_code': 401, 'expected_message': '密码错误，还可重试4次', 'expected_success': False, ...}\nauth_token = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjExNTUiLCJpYXQiOjE3NTM5NjgxMzcsImV4cCI6MTc1Mzk3NTMzN30.8Z0UL4YhRJFzi7N5EhkXevrBoOZeDF3M2eZnEcjJmSU'\nsmall_jpg_image = 'small_8676.jpg'\nlarge_jpg_image = 'large_5489.jpg'\nsmall_png_image = 'small_4360.png'\nlarge_png_image = 'large_3579.png'\nnon_image_file = 'test_1764.txt'\n\n    @allure.feature(\"用户认证模块\")\n    @pytest.mark.parametrize(\"case\", CASES)\n    def test_user_auth(case, auth_token, small_jpg_image, large_jpg_image, small_png_image, large_png_image, non_image_file):\n        allure.story(case[\"name\"])\n        allure.title(case[\"case_id\"] + \": \" + case[\"name\"])\n    \n        # 文件映射\n        file_map = {\n            \"test_avatar.jpg\": small_jpg_image,\n            \"large_avatar.jpg\": large_jpg_image,\n            \"test_avatar.png\": small_png_image,\n            \"large_avatar.png\": large_png_image,\n            \"test_file.txt\": non_image_file\n        }\n        # 预处理请求\n        request_data = preprocess_request(case, auth_token, file_map)\n    \n        # 发送请求\n        response = Request.send_request(\n            method=case[\"method\"],\n            endpoint=case[\"url\"],\n            json=request_data.get(\"json\"),\n            params=request_data.get(\"params\"),\n            headers=request_data.get(\"headers\"),\n            files=request_data.get(\"files\"),\n            token=auth_token\n        )\n    \n        # 断言\n>       assert_response(\n            response,\n            expected_code=case[\"expected_code\"],\n            expected_success=case.get(\"expected_success\"),\n            expected_message=case.get(\"expected_message\")\n        )\n\ntests\\test_user_auth.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [403]>, expected_code = 401\nexpected_success = False\nexpected_message = '密码错误，还可重试4次'\n\n    @allure.step(\"验证响应：状态码{expected_code}，消息{expected_message}\")\n    def assert_response(response, expected_code, expected_success=None, expected_message=None):\n        \"\"\"验证响应结果\"\"\"\n>       assert response.status_code == expected_code, \\\n            f\"状态码不符：预期{expected_code}，实际{response.status_code}\"\nE       AssertionError: 状态码不符：预期401，实际403\nE       assert 403 == 401\nE        +  where 403 = <Response [403]>.status_code\n\nutils\\test_utils.py:7: AssertionError"}, "steps": [{"name": "发送请求：'POST' '/auth/login'", "status": "passed", "attachments": [{"name": "请求信息", "source": "1cd9e11f-3ae1-4dc9-89a7-8aeed1a5e34d-attachment.json", "type": "application/json"}, {"name": "响应信息", "source": "bef88224-397b-4fbd-aaaf-52096a230b07-attachment.txt", "type": "text/plain"}, {"name": "响应体", "source": "7b7a2ba5-ef1f-447a-b6df-98e5693f90a9-attachment.json", "type": "application/json"}], "parameters": [{"name": "method", "value": "'POST'"}, {"name": "endpoint", "value": "'/auth/login'"}, {"name": "headers", "value": "{}"}, {"name": "params", "value": "{}"}, {"name": "json", "value": "{'username': 'admin1155', 'password': 'Wrong123'}"}, {"name": "files", "value": "None"}, {"name": "token", "value": "'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjExNTUiLCJpYXQiOjE3NTM5NjgxMzcsImV4cCI6MTc1Mzk3NTMzN30.8Z0UL4YhRJFzi7N5EhkXevrBoOZeDF3M2eZnEcjJmSU'"}], "start": 1753968172804, "stop": 1753968173025}, {"name": "验证响应：状态码401，消息'密码错误，还可重试4次'", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不符：预期401，实际403\nassert 403 == 401\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\utils\\test_utils.py\", line 7, in assert_response\n    assert response.status_code == expected_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "expected_code", "value": "401"}, {"name": "expected_success", "value": "False"}, {"name": "expected_message", "value": "'密码错误，还可重试4次'"}], "start": 1753968173025, "stop": 1753968173025}], "parameters": [{"name": "case", "value": "{'case_id': 'auth_019', 'name': '密码错误登录', 'method': 'POST', 'url': '/auth/login', 'json': {'username': 'admin1155', 'password': 'Wrong123'}, 'expected_code': 401, 'expected_success': False, 'expected_message': '密码错误，还可重试4次'}"}], "start": 1753968172804, "stop": 1753968173027, "uuid": "c6358682-29d8-4b47-bc16-4394bf11fd21", "historyId": "73a21e24c30644f4ccf646df1483681d", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "22368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}