{"uuid": "f3f348a2-cb4e-4ce1-a817-72f75f805027", "children": ["82d6f9ce-77c0-4241-be01-3915594e112e"], "befores": [{"name": "dynamic_test_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'list' object has no attribute 'get'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\test_user_auth.py\", line 78, in dynamic_test_user\n    json_data = case.get(\"json\", {})\n                ^^^^^^^^\n"}, "start": 1754635688723, "stop": 1754635688724}], "start": 1754635688723, "stop": 1754635688740}