{"name": "test_user_auth[case12]", "status": "broken", "statusDetails": {"message": "KeyError: 'url'", "trace": "@pytest.fixture(scope=\"session\")\n    def auth_token():\n        \"\"\"获取管理员token\"\"\"\n        with allure.step(\"登录获取token\"):\n>           response = Request.send_request(\n                \"POST\", \"/auth/login\",\n                json={\"username\": \"admin1155\", \"password\": \"admin1155\"}\n            )\nE           KeyError: 'url'\n\ntests\\conftest.py:20: KeyError"}, "parameters": [{"name": "case", "value": "{'case_id': 'auth_013', 'name': '密码与确认密码不一致', 'method': 'POST', 'url': '/auth/register', 'json': {'username': 'test_11koa7', 'password': 'Test123', 'confirmPassword': 'Test124', 'email': 'test_qngziz@example.com', 'verifyCode': '{verify_code}'}, 'expected_code': 400, 'expected_success': False, 'expected_message': '两次输入的密码不一致'}"}], "start": 1753967267402, "stop": 1753967267402, "uuid": "aaebe695-5aab-47d1-9f0a-9d1f18b57991", "historyId": "df47f06dd5984268fd1d0a49e21eab04", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "24212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}