{"name": "test_user_auth[case19]", "status": "broken", "statusDetails": {"message": "KeyError: 'url'", "trace": "@pytest.fixture(scope=\"session\")\n    def auth_token():\n        \"\"\"获取管理员token\"\"\"\n        with allure.step(\"登录获取token\"):\n>           response = Request.send_request(\n                \"POST\", \"/auth/login\",\n                json={\"username\": \"admin1155\", \"password\": \"admin1155\"}\n            )\nE           KeyError: 'url'\n\ntests\\conftest.py:20: KeyError"}, "parameters": [{"name": "case", "value": "{'case_id': 'auth_020', 'name': '账号锁定后登录', 'method': 'POST', 'url': '/auth/login', 'json': {'username': 'lockeduser', 'password': 'Test123456'}, 'expected_code': 401, 'expected_success': False, 'expected_message': '账号已锁定，请30分钟后再试'}"}], "start": 1753967267545, "stop": 1753967267545, "uuid": "eba311d3-3807-46cc-b958-07a1346ae41d", "historyId": "a4ee8e22309c74eb95727db2424ff9ae", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "24212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}