{"name": "test_user_auth[case26]", "status": "broken", "statusDetails": {"message": "KeyError: 'url'", "trace": "@pytest.fixture(scope=\"session\")\n    def auth_token():\n        \"\"\"获取管理员token\"\"\"\n        with allure.step(\"登录获取token\"):\n>           response = Request.send_request(\n                \"POST\", \"/auth/login\",\n                json={\"username\": \"admin1155\", \"password\": \"admin1155\"}\n            )\nE           KeyError: 'url'\n\ntests\\conftest.py:20: KeyError"}, "parameters": [{"name": "case", "value": "{'case_id': 'auth_027', 'name': '上传超过2MB的PNG图片', 'method': 'POST', 'url': '/auth/upload/avatar', 'headers': {'Authorization': 'Bearer ', 'Content-Type': 'multipart/form-data'}, 'files': {'file': 'large_avatar.png'}, 'expected_code': 400, 'expected_success': False, 'expected_message': '文件大小不能超过2MB'}"}], "start": 1753966889982, "stop": 1753966889982, "uuid": "e8c43857-832b-4fd8-bf69-7c367b8d8e5a", "historyId": "48cda2fab706b8c656c5aad4f5a4691b", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "10044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}